//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6Day3Ex6._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeWishTable
    {
        public string ShoeName { get; set; }
        public string Brand { get; set; }
        public decimal Price { get; set; }
        public string Style { get; set; }
        public string Color { get; set; }
    }
}
